version: '3'

networks:
    services-common-network:
        external: true

services:
    nginx:
        image: nginx
        volumes:
          - ./public:/usr/share/nginx/html
        networks:
          - services-common-network
